name: Daily NHL Standings

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 5 AM Eastern (9 AM UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python nhl_standings.py

      - name: Commit standings.txt using EndBug
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GageBot
          author_email: gage@example.com
          message: Daily NHL standings update
          add: standings.txt
