name: Daily NHL Standings

on:
  schedule:
    - cron: '0 9 * * *'  # 5 AM Eastern = 9 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python nhl_standings.py
      - name: Commit updated standings
        run: |
          git config --global user.name "GageBot"
          git config --global user.email "gage@example.com"
          git add standings.txt
          git commit -m "Daily NHL standings update"
          git push
